services:
   frontend-dev:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      volumes:
         - ./frontend:/app
         - /app/node_modules
      environment:
         - CHOKIDAR_USEPOLLING=true
         - VITE_API_BASE_URL=http://localhost:3000
         - VITE_PICTURES_URL=http://localhost:3000/pictures/
      ports:
         - "5173:5173"

   backend-dev:
      build:
         context: ./backend
         dockerfile: Dockerfile
      volumes:
         - ./backend:/app
         - /app/node_modules
      ports:
         - "3000:3000"
      environment:
         - CHOKIDAR_USEPOLLING=true
         - DATABASE_URL=postgresql://username:password@db-dev:5432/eshop?schema=public
         - JWT_SECRET=secret
         - PIC_PATH=./files
      depends_on:
         - db-dev
      healthcheck:
         test: ["CMD", "bash", "-c", "pg_isready -h db-dev -p 5432 || exit 1"]
         interval: 30s
         retries: 5
      command: >
         sh -c "npx prisma migrate dev &&
              node ./prisma/seed.js &&
              npm run start:dev -- --host"
      networks:
         - internal-network

   db-dev:
      image: postgres:16
      environment:
         POSTGRES_USER: username
         POSTGRES_PASSWORD: password
         POSTGRES_DB: eshop
      ports:
         - "5432:5432"
      networks:
         - internal-network

networks:
   internal-network:
      driver: bridge
